### ISSUE TITLE
What do people do if they're not doing RCOS for experience?

### ISSUE THREAD

**Issue by seveibar** [rcos/intro#8]

**Comment by t3dotgg** [comment]
If they're "not" doing RCOS for experience?

**Comment by seveibar** [comment]
Woops... thanks Theo

**Comment by t3dotgg** [comment]
Titles of issues can't be edited on Github, so I opened a separate issue to avoid confusion

https://github.com/rcos/intro/issues/10

**Comment by the-graytest** [comment]
They do it for credit!  ;P
